### ISSUE TITLE
how to for noobs

### ISSUE THREAD

**Issue by mihai-satmarean** [jovandeginste/jenkins-jobs-mattermost#2]
Hi, I am looking for the way to use that, but I am not really understanding.
can you please add some simple instructions.
Thank you!

**Comment by jovandeginste** [comment]
As a matter of fact, I'm not using this since 2 years or so. I would not recommend using it, but instead you should use Jenkinsfiles...

**Comment by mihai-satmarean** [comment]
Thanks!
I was looking for a way to send commands to a jenkins  in the form of curl
calls or similar from a mattermost chat without writing it myself :)
I thought this would do just that.
I have very simple scenario.

Thanks!

În vin., 16 nov. 2018 la 09:54, Jo Vandeginste <notifications@github.com> a
scris:

**Comment by jovandeginste** [comment]
I'm sorry, this is a totally different problem :-)

What this repo does, is configure part of a Jenkins job to report to Mattermost about its progress.
The part that actually does the reporting form Jenkins to Mattermost is a different project: https://github.com/jovandeginste/jenkins-mattermost-plugin

What you want (if I understand correctly) is the other direction: Mattermost triggering Jenkins builds...

**Comment by mihai-satmarean** [comment]
Yes! That is what I want . Any clue?
Thanks!

Pe 16 nov. 2018, la 13:28, Jo Vandeginste <notifications@github.com> a scris:

**Comment by jovandeginste** [comment]
You need to build a mattermost plugin for this, similar to a chatbot (eg. https://mattermost.com/blog/mattermost-recipe-how-to-create-a-chatbot-with-dialogflow-and-google-cloud-functions/)

**Comment by mihai-satmarean** [comment]
Ok 
Thanks!

Pe 16 nov. 2018, la 15:43, Jo Vandeginste <notifications@github.com> a scris:
